### ISSUE TITLE
使用 UPX 压缩是否可行？

### ISSUE THREAD

**Issue by NemoAlex** [kuoruan/openwrt-frp#11]
在我的QCA9531上测试，目前的版本经过UPX压缩以后，二进制文件只有3.5M，但是在设备上无法运行，表现为：运行后CPU占用率50%，程序没有任何输出。
搜索发现以前有一些人说UPX压缩后可以用，不知道是不是我哪里做得不对...

**Comment by NemoAlex** [comment]
刚发现squashfs的压缩比可以的...10M的文件上去只占4.6M，那其实也不用UPX了

**Comment by liammazy** [comment]
> 在我的QCA9531上测试，目前的版本经过UPX压缩以后，二进制文件只有3.5M，但是在设备上无法运行，表现为：运行后CPU占用率50%，程序没有任何输出。 搜索发现以前有一些人说UPX压缩后可以用，不知道是不是我哪里做得不对...

可能是UPX的版本不对，要用3.95，不能用最新版
