### ISSUE TITLE
麻烦加入本地http转https的功能

### ISSUE THREAD

**Issue by sonyxu** [kuoruan/openwrt-frp#16]
可能会有点麻烦 八成是要多一个文件夹放证书。
https://github.com/fatedier/frp#enable-https-for-local-http-service

如链接所示frp有本地http转https的功能。
对于开启了hsts的人来说由于本地要穿透的网页http、https混杂，所以有时候需要反代就很麻烦。因为在nginx上至少我不知道到怎么一个通配符里如何按情况反代不类型的连接。所以加入能统一成一样的https那么就方便很多了，所以为此麻烦加入一下这个功能。
在此表示感谢。

**Comment by 1032740078** [comment]
同求

**Comment by paladin4fan** [comment]
本身就支持……只是你要动手改配置文件 目前只用luci界面实现不了
