### ISSUE TITLE
LuCI 中配置的HTTP proxy无法生效

### ISSUE THREAD

**Issue by koala0529** [kuoruan/openwrt-frp#17]
/etc/init.d/frpc 文件中 217行中改成                 "heartbeat_interval" "heartbeat_timeout" "http_proxy"
就可以了

**Comment by kuoruan** [comment]
可以提交一个 PR

**Comment by koala0529** [comment]
已经申请提交到luci-app-frpc仓库了，你可以确认一下

**Comment by kuoruan** [comment]
Done.
