### ISSUE TITLE
frps 如何运行kcp模式

### ISSUE THREAD

**Issue by mazh3000** [kuoruan/openwrt-frp#2]

**Comment by kuoruan** [comment]
Please look over the official document: https://github.com/fatedier/frp/blob/master/README.md#support-kcp-protocol

**Comment by mazh3000** [comment]
改了之后, 正常tcp模式没问题, 但是kcp模式连接不通

**Comment by kuoruan** [comment]
Open a issue at official repository page, not here.

**Comment by mazh3000** [comment]
> 
> 
> Open a issue at official repository page, not here.

thank you
