### ISSUE TITLE
init script for frps?

### ISSUE THREAD

**Issue by lss4** [kuoruan/openwrt-frp#20]
I'm using the router for `frps` and I just found out there's no way to manage the `frps` instance.

Given there's no `luci-app-frps` counterpart like `frpc`, I have to put this line somewhere, or execute it manually whenever the router reboots.

`nohup frps -c <path-to-frps.ini> &`

Can anyone point me to a package for this? While the nohup method works for me, it's still a bit hackish.

**Comment by Taosky** [comment]
You can new a startup script. `vi /etc/init.d/frpserver`
```sh
#!/bin/sh /etc/rc.common
START=99

start(){
    frps -c <path-to-frps.ini> &
}
```
Add execute permission.
`chmod +x /etc/init.d/frpserver`

Now go to Luci - System -Startup. Enable it and start it.

**Comment by lss4** [comment]
Yeah, this is a good init script example. However, I'm building my own images with all the packages I need included in the system, so I can conveniently upgrade the router as well as the software I need to use on it later on, as well as saving some storage space.

For that, I worry about the possibility that a custom init script (other than those included with the system image) might not survive when flashing a newer image.

**Comment by kuoruan** [comment]
https://github.com/openwrt/packages/tree/master/net/frp
Frp is already in Openwrt offical repo, both client and server, you can try that one.

**Comment by lss4** [comment]
> https://github.com/openwrt/packages/tree/master/net/frp
> Frp is already in Openwrt offical repo, both client and server, you can try that one.

Sorry for a late response. Yeah, it seems the official OpenWrt's frp packages have the init scripts I wanted. Thanks.
