### ISSUE TITLE
Failed to compile openwrt-frp for openwrt-x86_64-19.07.7 on Ubuntu 20.04.

### ISSUE THREAD

**Issue by hongyi-zhao** [kuoruan/openwrt-frp#22]
Hi,

On Ubuntu 20.04, I try to compile openwrt-frp for openwrt-x86_64-19.07.7 but failed as shown below. 

See the following for the openwrt firmware version info for my case:
```
root@OpenWrt:~# cat /etc/openwrt_release 
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.7'
DISTRIB_REVISION='r11306-c4a6851c72'
DISTRIB_TARGET='x86/64'
DISTRIB_ARCH='x86_64'
DISTRIB_DESCRIPTION='OpenWrt 19.07.7 r11306-c4a6851c72'
DISTRIB_TAINTS=''
```
The openwrt master version info is shown below:

```
$ git log -1
commit 209c5918b511d9e406a094ba246a985b640e519f (HEAD -> master, origin/master, origin/HEAD)
Author: Vivek Unune <npcomplete13@gmail.com>
Date:   Fri Nov 13 08:43:00 2020 -0500
```
I compile openwrt-frp according to the guidance [here](https://github.com/kuoruan/openwrt-frp#%E7%BC%96%E8%AF%91%E8%AF%B4%E6%98%8E) with the following steps:
```

$ git clone https://github.com/kuoruan/openwrt-frp.git package/frp

$ ./scripts/feeds update -a
$ ./scripts/feeds install -a
  
$ make menuconfig

Network  ---> Web Servers/Proxies  ---> <*> frpc
Network  ---> Web Servers/Proxies  ---> <*> frps
 
$ make package/frp/{clean,compile} V=s
[...]
cp -fpR /home/werner/Public/repo/git.openwrt.org/openwrt/openwrt.git/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib/ld-musl-*.so* /home/werner/Public/repo/git.openwrt.org/openwrt/openwrt.git/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc/lib/
cp: cannot stat '/home/werner/Public/repo/git.openwrt.org/openwrt/openwrt.git/staging_dir/toolchain-x86_64_gcc-8.4.0_musl/lib/ld-musl-*.so*': No such file or directory
make[2]: *** [Makefile:728: /home/werner/Public/repo/git.openwrt.org/openwrt/openwrt.git/build_dir/target-x86_64_musl/toolchain/.pkgdir/libc.installed] Error 1
make[2]: Leaving directory '/home/werner/Public/repo/git.openwrt.org/openwrt/openwrt.git/package/libs/toolchain'
time: package/libs/toolchain/compile#0.28#0.15#0.39
    ERROR: package/libs/toolchain failed to build.
make[1]: *** [package/Makefile:114: package/libs/toolchain/compile] Error 1
make[1]: Leaving directory '/home/werner/Public/repo/git.openwrt.org/openwrt/openwrt.git'
make: *** [/home/werner/Public/repo/git.openwrt.org/openwrt/openwrt.git/include/toplevel.mk:230: package/frp/compile] Error 2
```

OTOH, I can successfully compile openwrt-frp from within [OpenWrt SDK](https://downloads.openwrt.org/releases/19.07.7/targets/x86/64/openwrt-sdk-19.07.7-x86-64_gcc-7.5.0_musl.Linux-x86_64.tar.xz) using the same above-mentioned steps. See the following for the generated ipk files:
```
$ find . -type f -name '*.ipk' | grep frp
./bin/packages/x86_64/base/frps_0.36.2-1_x86_64.ipk
./bin/packages/x86_64/base/frpc_0.36.2-1_x86_64.ipk
```

Any hints for solving this problem?

Regards,
HY

**Comment by hongyi-zhao** [comment]
Finally, I solved the problem with the following trick, though I don't know why these files are missing in the openwrt git repo.

According to the content of your [comile.sh](https://github.com/kuoruan/openwrt-frp/blob/5c59c18a1faacb4094e60642d2b9bd5e646dfbca/compile.sh#L13), I retrieved the snapshot version of the openwrt-sdk [here](https://downloads.openwrt.org/snapshots/targets/x86/64/openwrt-sdk-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz), and then copy the `toolchain-x86_64_gcc-8.4.0_musl` directory of the sdk to the corresponding location of the openwrt git repo. This fix the issue reported here.

Regards,
HY

**Comment by kuoruan** [comment]
Sorry for the late reply. Yes, you'd better use the snapshot version of OpenWrt SDK. Other versions not fully tested.
