### ISSUE TITLE
和这个（https://github.com/MvsCode/frp-onekey）一键frps搭建配合使用，提示：2019/09/07 14:29:26: frp服务启动失败，请检查服务端 “TCP多路复用(tcp_mux)”设置，确保与客户端完全一致！。

### ISSUE THREAD

**Issue by cindzzic** [kuoruan/openwrt-frp#5]

**Comment by cindzzic** [comment]
那个一键配置脚本tcpmux=true；路由器本地tcpmux=1;是这个设置的问题？

**Comment by kuoruan** [comment]
是否是配合我的 luci 使用的？
看看
```
/var/etc/frpc/frpc.main.ini
```
这个文件的内容，比较一下 tcp_mux 的值

**Comment by cindzzic** [comment]
> 
> 
> 是否是配合我的 luci 使用的？
> 看看
> 
> ```
> /var/etc/frpc/frpc.main.ini
> ```
> 
> 这个文件的内容，比较一下 tcp_mux 的值

看了，文件都是 tcp_mux=true。但是还是报同样的错误。我用的是这个luci（链接: https://pan.baidu.com/s/13WojsU-yzh9Wh13xKsPNow 提取码: x89d ）。

**Comment by kuoruan** [comment]
如果配置文件都对的话，看看服务端和客户端的版本是否一致，另外，如果配置都一致还出问题的话，换官方编译版本，或者向官方报 Bug
