### ISSUE TITLE
请问frps 如何修改配置文件呢？

### ISSUE THREAD

**Issue by tanpengsccd** [kuoruan/openwrt-frp#6]
![image](https://user-images.githubusercontent.com/13959880/66732292-e61d7380-ee8d-11e9-9b42-28849450a65e.png)
或者说怎么配置呢？

**Comment by tanpengsccd** [comment]
找到了！
启动项路径在 /etc/init.d/frps
配置文件路径在 /var/etc/frps.ini
不知道重启会不会失效

**Comment by tanpengsccd** [comment]
再次启动frps 配置文件 /var/etc/frps.ini 会回滚到默认配置。这是什么原因呢？

**Comment by tanpengsccd** [comment]
关闭启动项:frps后,修改 配置，再启动/重启 配置又恢复默认的了

**Comment by kuoruan** [comment]
我的包里边并不存在 /var/etc/frps.ini
请到对应作者下提交 issue

**Comment by tanpengsccd** [comment]
不好意思，确实不一样。
