### ISSUE TITLE
openwrt上安装frps，不能连接

### ISSUE THREAD

**Issue by hubanya** [kuoruan/openwrt-frp#8]
有外网ip的openwrt x86软路由上安装了frps，`frps.ini`配置文件如下：
```
[common]
bind_port = 7000
```

另一台电脑（不在这个路由器下）上安装了frpc，`frpc.ini`配置文件如下：
```
[common]
server_addr = xxx.xxx.xxx.xxx
server_port = 7000

[https-tcp]
type = tcp
local_ip = 127.0.0.1
local_port = 443
remote_port = 12345
custom_domains = example.com
```
如果用通过这个openwrt路由器上网的任何设备访问`https://example.com:12345`，都毫无问题，非常完美。但是用不是通过这个路由器上网的设备（比如手机4G）就访问不了。完全是小白，但是猜想可能是openwrt上某个防火墙设置有问题，瞎折腾了半天还是不行。防火墙上7000端口是打开的，不然路由器背后的设备也不可能访问。想请教一下大概可能是什么地方出了问题吗？谢谢！

**Comment by kuoruan** [comment]
打开 wan 端口的防火墙，允许外部访问

**Comment by hubanya** [comment]
请问是在这个地区打开吗？把wan的全部改成接受，但是还是不行。非常感谢！

![Untitled](https://user-images.githubusercontent.com/18040273/74813130-c1e80c80-532f-11ea-9eea-d6d1a49ddebb.png)

**Comment by kuoruan** [comment]
在外部能访问 OpenWrt 上的 luci 吗？

然后看看
```
netstat -npl | grep 12345
```

**Comment by hubanya** [comment]
昨天折腾一天，又按照你的办法全部检查了一遍。无论如何也找不到本地的问题。现在想想可能是这个外网IP所处的网络环境上加了防火墙。谢谢你指导。

**Comment by btxcrap** [comment]
我也遇到这个问题，查看/var/log/frpc.log，提示 connect 127.0.0.1:22 connection refused。检查防火墙设置也没有问题，最后是把 local_ip 127.0.0.1 换成路由器的内网IP就解决了。原因可能是 dropbear 的服务没有在 127.0.0.1:22 上，而是在 内网IP:22
